import { SampleCar } from "./types";

export const SAMPLE_CARS: SampleCar[] = [
  {
    id: "sample-1",
    title: "Maruti Suzuki Swift (Front Collision)",
    description: "Minor-to-moderate front bumper and headlight impact typical of city traffic collisions.",
    imageUrl: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=600&q=80",
    mockAssessment: {
      car_model_identified: "Maruti Suzuki Swift (2022 VXI)",
      overall_damage_severity: "Moderate",
      damage_details: [
        {
          part_name: "Front Bumper",
          damage_description: "Deep dent on the passenger side with scuff marks and paint peeling.",
          action_required: "Repair",
          estimated_cost_INR: 4800,
          damage_percentage: 12,
          bounding_box: [64, 12, 88, 88],
        },
        {
          part_name: "Right Headlight Assembly",
          damage_description: "Outer polycarbonate lens is cracked, and internal mounting clips are broken.",
          action_required: "Replace",
          estimated_cost_INR: 3500,
          damage_percentage: 28,
          bounding_box: [50, 68, 64, 86],
        },
        {
          part_name: "Left Fender Panel",
          damage_description: "Minor hairline scratch and paint rub from bumper misalignment.",
          action_required: "Repair",
          estimated_cost_INR: 1800,
          damage_percentage: 20,
          bounding_box: [42, 4, 64, 22],
        },
      ],
      total_estimated_cost_INR: 10100,
    },
  },
  {
    id: "sample-2",
    title: "Honda City (Side Panel Dent)",
    description: "Deep side swipe dents and heavy scratches along the driver-side doors.",
    imageUrl: "https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&w=600&q=80",
    mockAssessment: {
      car_model_identified: "Honda City (i-VTEC)",
      overall_damage_severity: "Moderate",
      damage_details: [
        {
          part_name: "Front Right Door Panel",
          damage_description: "Long horizontal scrape and moderate deformation along the door crease.",
          action_required: "Repair",
          estimated_cost_INR: 6500,
          damage_percentage: 30,
          bounding_box: [38, 20, 72, 54],
        },
        {
          part_name: "Rear Right Door Panel",
          damage_description: "Deep crease dent with bare metal exposed, requires minor welding and dent pulling.",
          action_required: "Repair",
          estimated_cost_INR: 7200,
          damage_percentage: 32,
          bounding_box: [38, 52, 72, 86],
        },
        {
          part_name: "Right Side View Mirror",
          damage_description: "Mirror housing is shattered, indicator LED strip is severed.",
          action_required: "Replace",
          estimated_cost_INR: 2800,
          damage_percentage: 45,
          bounding_box: [32, 16, 46, 28],
        },
      ],
      total_estimated_cost_INR: 16500,
    },
  },
  {
    id: "sample-3",
    title: "Hyundai i20 (Windshield Chip & Crack)",
    description: "Bullseye chip and spiderweb stress crack spanning across the front windshield.",
    imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=600&q=80",
    mockAssessment: {
      car_model_identified: "Hyundai i20 (Asta)",
      overall_damage_severity: "Minor",
      damage_details: [
        {
          part_name: "Front Windshield Glass",
          damage_description: "Spiderweb crack exceeding 15cm from a highway gravel impact. Impairs driver visibility.",
          action_required: "Replace",
          estimated_cost_INR: 7500,
          damage_percentage: 15,
          bounding_box: [16, 24, 42, 76],
        },
        {
          part_name: "Windshield Wiper Blades",
          damage_description: "Rubber torn from scraping against the cracked glass edge.",
          action_required: "Replace",
          estimated_cost_INR: 850,
          damage_percentage: 85,
          bounding_box: [38, 28, 48, 72],
        },
      ],
      total_estimated_cost_INR: 8350,
    },
  },
  {
    id: "sample-4",
    title: "Mahindra Thar (Severe Offroad Crash)",
    description: "Heavy frontal collision with severe structural and bumper collapse.",
    imageUrl: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=600&q=80",
    mockAssessment: {
      car_model_identified: "Mahindra Thar 4x4",
      overall_damage_severity: "Severe",
      damage_details: [
        {
          part_name: "Heavy Duty Front Bumper",
          damage_description: "Completely crushed, metal structure bent inwards, mounting points torn.",
          action_required: "Replace",
          estimated_cost_INR: 18500,
          damage_percentage: 85,
          bounding_box: [64, 10, 92, 90],
        },
        {
          part_name: "Front Grille & Radiator Mount",
          damage_description: "Grille shattered. Radiator assembly is pushed back and leaking coolant.",
          action_required: "Replace",
          estimated_cost_INR: 22000,
          damage_percentage: 90,
          bounding_box: [52, 32, 72, 68],
        },
        {
          part_name: "Engine Hood Panel",
          damage_description: "Crumpled in the center, hinges bent out of alignment. Latches broken.",
          action_required: "Replace",
          estimated_cost_INR: 14000,
          damage_percentage: 65,
          bounding_box: [34, 18, 58, 82],
        },
        {
          part_name: "LED Headlight Assemblies (Pair)",
          damage_description: "Both left and right headlamp brackets snapped, glass housings pulverized.",
          action_required: "Replace",
          estimated_cost_INR: 9500,
          damage_percentage: 95,
          bounding_box: [48, 14, 65, 86],
        },
      ],
      total_estimated_cost_INR: 64000,
    },
  },
];
